services:
  garage-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Garage__Esp32BaseUrl=http://192.168.1.50
      - Garage__Esp32TriggerPath=/open
      - Jwt__Issuer=GarageProject
      - Jwt__Audience=GarageMobile
      - Jwt__SigningKey=CHANGE_ME_TO_A_LONG_RANDOM_SECRET
      - Jwt__TokenMinutes=60
      - Jwt__Username=admin
      - Jwt__Password=changeme
